name: queee_calculator
description: "AI驱动的个性化计算器 - 用自然语言定制你的专属计算器"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  math_expressions: ^3.0.0
  audioplayers: ^5.2.1
  image_picker: ^1.0.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/sounds/cyberpunk/
    - assets/sounds/minimal/
    - assets/sounds/nature/
    - assets/themes/

# The following adds the Cupertino Icons font to your application. 