name: queee_calculator
description: "AI驱动的个性化计算器 - 用自然语言定制你的专属计算器"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  math_expressions: ^3.0.0
  audioplayers: ^6.1.0  # 音效播放支持
  just_audio: ^0.9.36
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true 

  # The following line ensures that the Material Icons font is 